/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "OpenAiApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "dplAPVectorDB": {
      "putFunction": string
      "queryFunction": string
      "removeFunction": string
      "type": "sst.aws.Vector"
    }
    "iam-dpl-rag-api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "iam-dpl-rag-bucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
  }
}
